backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow
site_url: https://kailoon.com
display_url: https://kailoon.com
logo_url: https://res.cloudinary.com/kailoon/image/upload/v1610896578/kailoon.com/logo_stqiiw.svg
show_preview_links: true

# media
media_library:
  name: cloudinary
  config:
    cloud_name: kailoon
    api_key: 373569654927936

#collections
collections:
  - name: 'posts'
    label: 'Post'
    folder: 'src/posts'
    create: true
    slug: '{{year}}/{{month}}/{{slug}}'
    preview_paath: 'posts/{{year}}/{{month}}/{{slug}}'
    fields:
      - { label: 'Layout', name: 'single', widget: 'hidden' }
      - { label: 'Meta Title', name: 'metaTitle', widget: 'string' }
      - { label: 'Meta Description', name: 'metaDescription', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Sub Heading', name: 'subHeading', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured Image',
          name: 'featuredImg',
          widget: 'image',
          required: false
        }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['posts'] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'published',
          name: 'published',
          widget: 'boolean',
          default: false
        }
